repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
      # Run the import sorter.
      - id: ruff
        name: ruff-import-sorting
        args: [--select, I, --fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: 'whitespaces.ws$'
      - id: check-json
        files: \.json$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
      - id: mypy
        args: [--no-warn-unused-ignores]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        entry: yamllint
        language: python
        types: [file, yaml]
  - repo: https://github.com/terrencepreilly/darglint
    rev: 'v1.8.1'
    hooks:
      - id: darglint
        name: darglint
        description: '`darglint` is a tool for linting python docstrings.'
        entry: darglint
        language: python
        types: [python]
        require_serial: true
