#!/bin/bash

# Directory to output generated files (optional)
GRAMMAR_DIR="wandelscript/grammar"

# Ensure output directory exists
if [ ! -d "$OUTPUT_DIR" ]; then
  echo "$OUTPUT_DIR does not exist."
fi

# Move to the grammar directory to run the ANTLR command
cd "$GRAMMAR_DIR" || { echo "Failed to access $GRAMMAR_DIR"; exit 1; }

# Remove existing Python files generated by ANTLR in the current directory or output directory
echo "Cleaning up old generated files..."
rm -f wandelscriptLexer.interp
rm -f wandelscriptLexer.py
rm -f wandelscriptLexer.tokens
rm -f wandelscriptParser.interp
rm -f wandelscriptParser.py
rm -f wandelscriptParser.tokens
rm -f wandelscriptParserListener.py
rm -f wandelscriptParserVisitor.py

# Run ANTLR to generate Python3 files with the visitor pattern
echo "Running ANTLR to generate parser and lexer..."
antlr -Dlanguage=Python3 -visitor *.g4

# Provide feedback to the user
if [ $? -eq 0 ]; then
  echo "ANTLR generation complete. Files are located in $GRAMMAR_DIR."
else
  echo "ANTLR generation failed. Please check for errors."
fi

cd - > /dev/null