name: Typecheck, Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Python environment
        run: |
          pip install poetry
          poetry install

      - name: Check formatting with ruff
        run: poetry run ruff format --check .

      - name: Check import order
        run: poetry run ruff check --select I

      - name: Check ruff for linting
        run: poetry run ruff check .

      - name: Typecheck
        run: poetry run mypy

      - name: Run tests
        run: |
          PYTHONPATH=. poetry run pytest -rs -v
