---
name: "Typecheck, Lint and Format"
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Python environment
        run: |
          pip install uv
          uv sync --group dev

      - name: Check formatting with ruff
        run: uv run ruff format --check .

      - name: Check import order
        run: uv run ruff check --select I

      - name: Check ruff for linting
        run: uv run ruff check .

      - name: Typecheck
        run: uv run mypy

      - name: Run tests
        run: |
          PYTHONPATH=. uv run pytest wandelscript/
